import { Request, Response } from "express";
import { z } from "zod";
import { User } from "../models/User";
import { Patient } from "../models/Patient";
import { signToken } from "../services/token.service";
import { ok } from "../types";

export const RegisterSchema = z.object({
  name: z.string().min(2),
  email: z.string().email(),
  password: z.string().min(8),
  role: z.enum(["doctor", "guardian", "patient", "admin"]),
  // Doctor fields
  specialization: z.string().optional(),
  licenseNumber: z.string().optional(),
  // Guardian fields
  patientBotId: z.string().optional(),
  relationship: z.string().optional(),
  // Patient fields
  age: z.number().optional(),
  gender: z.enum(["male", "female", "other"]).optional(),
  healthGoal: z.string().optional(),
  patientName: z.string().optional(),
  conditions: z.array(z.string()).optional(),
});

export const LoginSchema = z.object({
  email: z.string().email(),
  password: z.string().min(1),
});

export async function register(req: Request, res: Response): Promise<void> {
  const body = req.body as z.infer<typeof RegisterSchema>;

  const existing = await User.findOne({ email: body.email });
  if (existing) {
    res
      .status(409)
      .json({ success: false, error: "Email already registered." });
    return;
  }

  const user = new User({
    name: body.name,
    email: body.email,
    passwordHash: body.password, // pre-save hook will hash it
    role: body.role,
    specialization: body.specialization,
    licenseNumber: body.licenseNumber,
    patientBotId: body.patientBotId,
    relationship: body.relationship,
  });

  await user.save();

  // If role is patient, create Patient document with same _id as User
  if (body.role === "patient") {
    const patient = new Patient({
      _id: user._id, // Match the user _id for consistent identification
      name: body.name,
      age: body.age,
      gender: body.gender,
      conditions: body.conditions || [],
      notes: body.healthGoal,
      // botId is generated by us
      botId: `bot_${user._id.toString().slice(-6)}`,
    });
    await patient.save();

    // Also update the user document with this botId
    user.patientBotId = patient.botId;
    await user.save();
  } else if (body.role === "guardian") {
    // 1. Create Patient User (User model)
    const patientUser = new User({
      name: body.patientName || `${body.name}'s Patient`,
      email: `patient_${user._id.toString()}@careplus.local`,
      passwordHash:
        body.password ||
        `${body.patientName?.split(" ")[0].toLocaleLowerCase()}1234`,
      role: "patient",
    });

    const botId = `bot_${patientUser._id.toString().slice(-6)}`;
    patientUser.patientBotId = botId;
    await patientUser.save();

    // 2. Create Patient Record (Patient model)
    const patient = new Patient({
      _id: patientUser._id, // Share the same ID as the User record
      name: body.patientName || `${body.name}'s Patient`,
      age: body.age,
      gender: body.gender,
      conditions: body.conditions || [],
      notes: body.healthGoal,
      guardianId: user._id,
      guardianName: user.name,
      botId: botId,
    });
    await patient.save();

    // 3. Link guardian to the generated patient botId
    user.patientBotId = botId;
    await user.save();
  }

  const token = signToken(user._id.toString(), user.email, user.role);
  res.status(201).json(ok({ token, user }, "Account created successfully."));
}

export async function login(req: Request, res: Response): Promise<void> {
  const { email, password } = req.body as z.infer<typeof LoginSchema>;

  const user = await User.findOne({ email }).select("+passwordHash");
  if (!user || !user.isActive) {
    res.status(401).json({ success: false, error: "Invalid credentials." });
    return;
  }

  const valid = await user.comparePassword(password);
  if (!valid) {
    res.status(401).json({ success: false, error: "Invalid credentials." });
    return;
  }

  const token = signToken(user._id.toString(), user.email, user.role);

  // Return user without password
  const safeUser = user.toJSON();
  res.json(ok({ token, user: safeUser }, "Login successful."));
}

export async function me(req: Request, res: Response): Promise<void> {
  const user = await User.findById(req.user!.userId);
  if (!user) {
    res.status(404).json({ success: false, error: "User not found." });
    return;
  }
  res.json(ok(user));
}

export const UpdateProfileSchema = z.object({
  name: z.string().min(2, "Name must be at least 2 characters").optional(),
  email: z.string().email("Invalid email format").optional(),
  phoneNumber: z.string().optional(),
  address: z.string().optional(),
  avatar: z.string().optional(),
  specialization: z.string().optional(),
  licenseNumber: z.string().optional(),
  relationship: z.string().optional(),
  currentPassword: z.string().optional(),
});

export const ChangePasswordSchema = z.object({
  currentPassword: z.string().min(1, "Current password is required"),
  newPassword: z.string()
    .min(8, "New password must be at least 8 characters long")
    .refine((val) => /[A-Z]/.test(val), { message: "New password must contain at least one uppercase letter" })
    .refine((val) => /[a-z]/.test(val), { message: "New password must contain at least one lowercase letter" })
    .refine((val) => /[0-9]/.test(val), { message: "New password must contain at least one number" }),
});

export async function updateMe(req: Request, res: Response): Promise<void> {
  const body = req.body as z.infer<typeof UpdateProfileSchema>;
  
  const user = await User.findById(req.user!.userId).select("+passwordHash");
  if (!user) {
    res.status(404).json({ success: false, error: "User not found." });
    return;
  }

  // Security Check: Re-authentication before sensitive changes (email change)
  if (body.email !== undefined && body.email.toLowerCase() !== user.email.toLowerCase()) {
    if (!body.currentPassword) {
      res.status(400).json({
        success: false,
        error: "Current password is required to change your email address.",
      });
      return;
    }
    const isPasswordValid = await user.comparePassword(body.currentPassword);
    if (!isPasswordValid) {
      res.status(401).json({
        success: false,
        error: "Incorrect current password. Re-authentication failed.",
      });
      return;
    }

    // Check if email is already taken
    const existing = await User.findOne({ email: body.email.toLowerCase() });
    if (existing && existing._id.toString() !== user._id.toString()) {
      res.status(409).json({
        success: false,
        error: "Email address is already in use by another account.",
      });
      return;
    }
  }

  const allowed: (keyof typeof body)[] = [
    "name",
    "email",
    "phoneNumber",
    "address",
    "avatar",
    "specialization",
    "licenseNumber",
    "patientBotId",
    "relationship",
  ];

  for (const key of allowed) {
    if (body[key] !== undefined) {
      (user as any)[key] = body[key];
    }
  }

  await user.save();
  res.json(ok(user, "Profile updated successfully."));
}

export async function changePassword(req: Request, res: Response): Promise<void> {
  const { currentPassword, newPassword } = req.body as z.infer<typeof ChangePasswordSchema>;

  const user = await User.findById(req.user!.userId).select("+passwordHash");
  if (!user) {
    res.status(404).json({ success: false, error: "User not found." });
    return;
  }

  const isPasswordValid = await user.comparePassword(currentPassword);
  if (!isPasswordValid) {
    res.status(401).json({
      success: false,
      error: "Incorrect current password.",
    });
    return;
  }

  user.passwordHash = newPassword;
  await user.save();

  res.json(ok(null, "Password changed successfully."));
}


export async function verifyGoogleToken(req: Request, res: Response): Promise<void> {
  const { idToken } = req.body;
  if (!idToken) {
    res.status(400).json({ success: false, error: "ID token is required." });
    return;
  }

  try {
    const response = await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${idToken}`);
    if (!response.ok) {
      res.status(400).json({ success: false, error: "Invalid Google token." });
      return;
    }

    const payload: any = await response.json();
    const clientId = process.env.GOOGLE_CLIENT_ID || "44430947651-mmos6g35gibdn6bejvfkk8am8322m1tn.apps.googleusercontent.com";
    if (payload.aud !== clientId) {
      res.status(400).json({ success: false, error: "Token client ID mismatch." });
      return;
    }

    if (!payload.email_verified) {
      res.status(400).json({ success: false, error: "Google email is not verified." });
      return;
    }

    res.json({ success: true, email: payload.email });
  } catch (err) {
    console.error(err);
    res.status(500).json({ success: false, error: "Server error verifying Google token." });
  }
}

